### ISSUE TITLE
Does it work on the newest version of Hexo?

### ISSUE THREAD

**Issue by Anthonyeef** [joyceim/hexo-theme-apollo#5]
Many themes have modified to fit the new version of Hexo. So I am wondering will this work on it. And will it cause any problem if I am already with the new version of Hexo?
BTW, nice work of this theme. It's my cup of tea:)

**Comment by DreaminginCodeZH** [comment]
I'm using my own fork of this theme and so far it worked well for me, but I'm not sure whether this is made possible by my own changes.

However it seems that [Hexo 3 did not break things used by this theme](https://github.com/hexojs/hexo/wiki/Breaking-Changes-in-Hexo-3.0), so the upstream version might work for you as well.

**Comment by Anthonyeef** [comment]
I tried it and it works well. Thanks dude :)
